name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
        C:\vcpkg\bootstrap-vcpkg.bat
        C:\vcpkg\vcpkg integrate install

    - name: Install dependencies
      run: |
        C:\vcpkg\vcpkg install lz4:x64-windows
        C:\vcpkg\vcpkg install liblzma:x64-windows
        C:\vcpkg\vcpkg install openssl:x64-windows

    - name: Create build directory
      run: mkdir build

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 src/Native/ABProcessorNative.vcxproj

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ABProcessorNative
        path: |
          bin/x64/Release/ABProcessorNative.dll
          bin/x64/Release/*.dll
        compression-level: 9
